spring:
  #邮箱配置
  mail:
    host: smtp.sina.com
    username: daw2019@sina.com
    #邮箱的授权码
    password: dcf74a4958d3bc39
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    #邮箱发送等信息配置
    config:
      toMails:
        - daw2019@sina.com
        - 1109429385@qq.com
        - aizgw2012@163.com
      fromAlias: 鑫平台研发部
      tflName: mail.tfl
